services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: neohabit-app
    volumes:
      - ./html:/var/www/html
    networks:
      - app_network
    ports:
      - "8180:80"

  mysql:
    image: mysql:8.1.0
    container_name: neohabit-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: neohabit_db
      MYSQL_USER: felipe
      MYSQL_PASSWORD: fpm
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    ports:
      - "3316:3306"

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
