services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application-app
    volumes:
      - ./html:/var/www/html
      - ./container-conf/openssl-keys:/app/openssl-keys
    networks:
      - application_network
    ports:
      - "8180:80"

  mysql:
    image: mysql:8.1.0
    container_name: application-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: application_db
      MYSQL_USER: application
      MYSQL_PASSWORD: application123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-conf:/var/db-conf
    networks:
      - application_network
    ports:
      - "3316:3306"

networks:
  application_network:
    driver: bridge

volumes:
  mysql_data:
